### ISSUE TITLE
Can't install add-in

### ISSUE THREAD

**Issue by Stevod** [Linusnie/blender-plots#1]
I'm keen to use this for vis, but I have been unable to install this as per instructions. Tried initially using Edit>Preferences>Add-ons to install the .zip file in Blender 3.2, but it didn't appear in refreshed add-on list but with no error messages.

I then install 3.1.2 which had same problem, and finally cloned the repo which give the following messages in system console on use:

Read prefs: C:\Users\david\AppData\Roaming\Blender Foundation\Blender\3.1\config\userpref.blend
Modules Installed () from 'C:\\Users\\<user>\\Downloads\\blender_plots-main.zip' into 'C:\\Users\\<user>\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons'
Info: Deleted 1 object(s)

Traceback (most recent call last):
  File "\Text", line 7, in <module>
AttributeError: module 'blender_plots' has no attribute 'Scatter'
Error: Python script failed, check the message in the system console

I'm on windows 11. Are you able to provide any guidance please?

**Comment by Linusnie** [comment]
hi, thanks for reporting this! Looks like I forgot to include the init file... could you try again on the latest patch?

Edit: found another problem when trying a fresh install myself, will push another patch later today. Hold off on trying it for now

**Comment by Stevod** [comment]
Great thanks. Had just twigged the init file, though it made no difference when I added it.

**Comment by Linusnie** [comment]
You were probably missing `from .scatter import *` if you added an empty init, but it should work now :crossed_fingers:

I updated the installation instructions as well, looks like the .zip-method is not as convenient as I'd like since github adds the branch name to the folder name which breaks imports. So it'll need to be renamed manually

 I'd be interested to hear if you have some preferred way of installing addons from github actually

**Comment by Linusnie** [comment]
Heads up: pushed another update which means the original download .zip -> install should work with no extra steps now!
 https://github.com/Linusnie/blender-plots/commit/bca19060a0542741ebb35025d10b0782e5f47e7c

**Comment by Stevod** [comment]
All working fine now. Not sure why it tries to install under AppData/Roaming on Windows, but that's linked into the correct addons folder under Program files, and so should should work seamlessly. It didn't initially for me following Preferences install of the zip, so I just copied the folder from Roaming to correct addons directory under Program Files; deleted it from Roaming, and it works fine now.

Thanks for the effort :)

**Comment by Linusnie** [comment]
awesome! Blender usually puts external addons in a different folder, on ubuntu it's /home/user/.config for example, it should work from there as well
