### ISSUE TITLE
Am able to use Scatter but without color

### ISSUE THREAD

**Issue by sharun-s** [Linusnie/blender-plots#4]
Not too familiar with numpy (or blender for that matter) so maybe I am doing something wrong. This is what I have tried...

bplt.Scatter(np.array([ (1,0,0), (3,0,0)]), color=(1,0,0) )

It draws the cubes but no color

**Comment by Linusnie** [comment]
your viewport shading mode is probably set to solid, try setting it to material preview or rendered (top right corner)
![Screenshot from 2023-10-20 21-59-43](https://github.com/Linusnie/blender-plots/assets/12471058/fd5c4bc2-ad3f-4e1f-a10f-d3d85f125b1e)

**Comment by sharun-s** [comment]
Oh man! Feels like I tried pressing every button other than that :facepalm: Sorry to bother you. And thank you for this cool addon! It is helping me understand how the python interface work.
