### ISSUE TITLE
AttributeError runing sample code in blender 4.0

### ISSUE THREAD

**Issue by fish8** [Linusnie/blender-plots#5]
While trying the code provided with install document:
import numpy as np
import blender_plots as bplt
n, l = 150, 100
x, y = np.meshgrid(np.linspace(0, l, n), np.linspace(0, l, n))
x, y = x.ravel(), y.ravel()

It gives an error message:

z = np.sin(2*np.pi * x / l)*np.sin(2*np.pi * y / l) * 20
bplt.Scatter(x, y, z, color=(1, 0, 0), name="red")
  """Create new node group, useful in blender 3.2 since node group is not added to node modifiers by default."""
    group = bpy.data.node_groups.new("Geometry Nodes", 'GeometryNodeTree')
--> group.inputs.new('NodeSocketGeometry', "Geometry")
    group.outputs.new('NodeSocketGeometry', "Geometry")
    input_node = group.nodes.new('NodeGroupInput')

AttributeError: 'GeometryNodeTree' object has no attribute 'inputs'

Is blender 4.0 supported? Thanks.

**Comment by Linusnie** [comment]
Hi, thank you for reporting this. Most likely an issue with Blender 4.0, I'll look into it when I get some time. The latest version I have  tried is 3.5

**Comment by Linusnie** [comment]
this should be fixed as of 729e8a6c0c64524b52e63357edcc4532d3ad3304!

**Comment by fish8** [comment]
Great! I will try it asap. Thanks a lot.

**Comment by fish8** [comment]
It works fine. Thanks.

**Comment by Linusnie** [comment]
@fish8 great! thanks for confirming
