### ISSUE TITLE
Blender crashes with Animation example

### ISSUE THREAD

**Issue by hdf** [Linusnie/blender-plots#8]
When creating a new blender file, and adding the animation example, if I only add the red scatter plot, it works, but only barely, however when adding the blue one, even if only by itself, blender crashes. And even just the red one will crash, when trying to render. I have 32GB ram, and an RTX 3060 with 12GB ram. The crash is always an EXCEPTION_ACCESS_VIOLATION.

How did you create that animation video? Does your machine have even more GPU memory?

Also, would it be possible to create an animation mode, where there is no interpolation, and only one frame is loaded at a time?

**Comment by hdf** [comment]
Just noticed, after reducing n to a lower number, there is no crash, but all the frame states get rendered at once on top of one another, and when hitting play, they all disappear. I'm using Blender 4.2.1.

![kép](https://github.com/user-attachments/assets/6e9d11c6-a0fe-4a88-93f7-bc9ebbc9f590)

**Comment by hdf** [comment]
Found the problem:
https://github.com/Linusnie/blender-plots/blob/c63003605a575730a6753b4b4f742897541619d8/blender_plots/blender_utils.py#L247
Changing [1] to [0] here, makes it work as expected.
This is what I see in my Geometry Node Editor (after fixing the bug):
![kép](https://github.com/user-attachments/assets/e9886667-26b1-426a-9973-7f4f33de5ee5)
frame_index.outputs[1] is Exists (bool), but we need Attribute (float).

**Comment by Linusnie** [comment]
hi @hdf thank you for reporting this (and finding the issue!). I get the same error with blender 4.2.1.

I'll look into making a backward-compatible fix. In the meantime, I have checked that the example still works on v4.0.1 if you are able to downgrade

**Comment by Linusnie** [comment]
@hdf should work as of https://github.com/Linusnie/blender-plots/commit/b4a537417159c46ad26988f98f8e9da2fc77e477, I replaced the index with a string key.
